### ISSUE TITLE
we need to update the lastest repo for `mongodb-org`

### ISSUE THREAD

**Issue by chrisduong** [sous-chefs/mongodb#40] opened 2015-06-09 03:46 UTC
Hi,

I believe, 10gen company has updated its new repo for `mongodb-org`. To use the latest stable release, we have to use this **new repo uri**. From **http://downloads-distro.mongodb.org/repo/#{node[:mongodb][:apt_repo]}** to **http://repo.mongodb.org/apt/ubuntu**.

``` ruby
  # Suggested new repo uri 
  apt_repository "#{node['mongodb']['package_name']}" do
    uri "http://repo.mongodb.org/apt/#{node['platform']}"
    distribution "#{node['lsb']['codename']}/#{node['mongodb']['package_name']}/stable"
    components ['multiverse']
    keyserver 'hkp://keyserver.ubuntu.com:80'
    key '7F0CEB10'
    action :add
  end
```

**Comment by triccardi-systran** [comment] 2015-06-09 07:21
This is to get MongoDB 3.0 isn't it?
Has anyone tested the rest of this cookbook with MongoDB 3.0?
To support 3.0 we would also need a way to force an old version of MongoDB, as upgrading to 3.0 could break things on the user side.
And maybe we could keep MongoDB 2.6 as default for now, otherwise we would need a major version bump for the cookbook.

**Comment by chrisduong** [comment] 2015-06-09 08:23
I believe the current cookbook cannot install MongoDB 3.x. 
Because the MongoDB repo is old, that repo uri only install MongoDB 2.x (2.6.10 is max at the moment).
We can define a new name for the latest repo, or rename the old repo so they are not conflict.

**Comment by luishdez** [comment] 2015-06-18 22:00
Adding an option `node['mongodb']['version']` could help to handle multiple versions and chose the repo based on that. It could solve other problems too. See: https://github.com/chef-brigade/mongodb-cookbook/pull/22

**Comment by gtaber** [comment] 2015-07-10 16:57
So is there currently a way to force the installation of the latest stable version using this cookbook? I'm getting version 2.4.9, but it would be great to get 3.0.4 if possible?

**Comment by luishdez** [comment] 2015-07-10 17:27
The repo that is setup only goes up to 2.6. I'm adding the support for 3.0 to the roadmap

**Comment by rex** [comment] 2015-07-13 13:41
@luishdez I completely agree that **default** support for `>3.0` is a must have. MongoDB `3.x` is already deployed in production to a huge number of users, there's no reason we shouldn't enable support for it. 

Remember that we need to offer the end user configurable options to specify the specific version of MongoDB that they need and ensure that the cookbook has no bugs with different versions.

**Comment by gtaber** [comment] 2015-07-22 17:33
Is there a timeline to incorporate the 10G MongoDB 3.0 repo and compatibility into this cookbook?

**Comment by DrMerlin** [comment] 2015-07-28 22:08
+1

**Comment by rex** [comment] 2015-07-29 15:00
@gtaber @DrMerlin As we only recently inherited control of this cookbook, we're still in the evaluation process of seeing exactly what we're working with. Officially supporting `>=3.0` is a huge item on our to-do list. At the moment, though, we're still working on getting all the tests passing for the cookbook in its current state. Once we get that ironed out, which should be very soon, our primary focus is going to be on bringing it up to scratch in terms of configurable version support *including* `>=3.0`. 

cc @zarry

**Comment by DrMerlin** [comment] 2015-07-30 19:28
Sounds great!  I'm just glad someone is picking up where edelight left off.

**Comment by joune** [comment] 2015-10-05 15:55
+1 for support of 3.0

**Comment by melechi** [comment] 2015-11-04 15:48
+1

**Comment by joune** [comment] 2016-01-29 08:53
Hi,
it's been 4 months and mongodb is now at version 3.2.1; just wondering; is this still cookbook maintained? Is there a more recent one somewhere?
Thanks to all.

**Comment by joune** [comment] 2016-01-29 17:27
Ok, I think I found the answer to my question, here: https://github.com/sunggun-yu/chef-mongodb3

**Comment by gtaber** [comment] 2016-01-29 17:34
Thank you!

On Jan 29, 2016, at 9:27 AM, Arjun Panday <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, I think I found the answer to my question, here: https://github.com/sunggun-yu/chef-mongodb3

**Comment by chrisduong** [comment] 2016-01-31 07:34
I think the same thing. :)

**Comment by triccardi-systran** [comment] 2016-02-01 11:27
The issue is still not fixed in this mongodb cookbook, reopening.

**Comment by shortdudey123** [comment] 2017-04-12 03:50
Completed in v1 rewrite

**Closed by shortdudey123** 2017-04-12 03:50 UTC
