### ISSUE TITLE
Python deprecation error on new install

### ISSUE THREAD

**Issue by androidfanatic** [sous-chefs/mongodb#154] opened 2017-05-15 06:49 UTC
$ knife cookbook site install sc-mongodb
...

Pristine copy branch (chef-vendor-python) exists, switching to it.

WARNING: DEPRECATION: This cookbook has been deprecated. It has been replaced by poise-python.

WARNING: Use --force to force download deprecated cookbook.

Removing pre-existing version.

Uncompressing python version 1.4.6.

ERROR: Errno::ENOENT: No such file or directory @ rb_sysopen - /root/chef-repo/cookbooks/python.tar.gz

**Comment by shortdudey123** [comment] 2017-05-15 07:05
Dupe of https://github.com/sous-chefs/mongodb/issues/119
This has already been accounted for in the rewrite that is in progress

**Closed by shortdudey123** 2017-05-15 07:05 UTC
