### ISSUE TITLE
User management KO : "Could not locate Gemfile"

### ISSUE THREAD

**Issue by jmcollin78** [sous-chefs/mongodb#93] opened 2015-10-04 17:58 UTC
Hi there,

Running the "master" branch of this cookbook with "replicatsets" recipe and user_management leads to the following error:

<pre>
[2015-10-04T14:27:01+00:00] INFO: Processing package[mongodb-org] action install (mongodb::install line 78)
[2015-10-04T14:27:05+00:00] INFO: package[mongodb-org] installing mongodb-org-2.6.11-1 from mongodb repository
[2015-10-04T14:27:49+00:00] INFO: Processing ruby_block[chef_gem_at_converge_time] action run (mongodb::replicaset line 25)
 
================================================================================
Error executing action `run` on resource 'ruby_block[chef_gem_at_converge_time]'
================================================================================
 
 
Bundler::GemfileNotFound
------------------------
Could not locate Gemfile
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/mongodb/recipes/replicaset.rb:29:in `block (3 levels) in from_file'
/var/lib/aws/opsworks/cache.stage2/cookbooks/mongodb/recipes/replicaset.rb:27:in `each'
/var/lib/aws/opsworks/cache.stage2/cookbooks/mongodb/recipes/replicaset.rb:27:in `block (2 levels) in from_file'
 
 
Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/mongodb/recipes/replicaset.rb
 
25: ruby_block 'chef_gem_at_converge_time' do
26:   block do
27:     node['mongodb']['ruby_gems'].each do |gem, version|
28:       version = Gem::Dependency.new(gem, version)
29:       Chef::Provider::Package::Rubygems::GemEnvironment.new.install(version)
30:     end
31:   end
32: end
33: 
 
 
 
Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/mongodb/recipes/replicaset.rb:25:in `from_file'
 
ruby_block("chef_gem_at_converge_time") do
action "run"
retries 0
retry_delay 2
block_name "chef_gem_at_converge_time"
cookbook_name "mongodb"
recipe_name "replicaset"
block #<Proc:0x00560c8bee3a48@/var/lib/aws/opsworks/cache.stage2/cookbooks/mongodb/recipes/replicaset.rb:26>
end<
</pre>

The users are not created.
I don't know if it has something to do with replicatsets. I guess no.

My wrapper wookbook:

<pre>
include_recipe "mongodb::10gen_repo"
include_recipe "mongodb::replicaset"
include_recipe "mongodb::user_management"
</pre>

My attributes:

<pre>
include_attribute 'appconfig::config'

default['mongodb']['config']['dbpath'] = '/data'
default['mongodb']['config']['rest'] =false
default['mongodb']['config']['smallfiles'] =true
default['mongodb']['admin']['password'] = 'theadminpassword'
default['mongodb']['users'] = [
        {
                'username' => 'testu',
                'password' => 'testu',
                'roles' => %w(readWrite),
                'database' => default['appconfig']['mongodb']['database']
        }
]

default['mongodb']['cluster_name'] = 'int-mgo-cluster'
default['mongodb']['config']['replSet'] = 'int-mgo-replset'
</pre>

I also notice this warning at the end of the log file:

<pre>
[2015-10-04T14:28:03+00:00] INFO: Processing ruby_block[config_replicaset] action create (mongodb::replicaset line 225)
** Notice: The native BSON extension was not loaded. **
 
For optimal performance, use of the BSON extension is recommended.
 
To enable the extension make sure ENV['BSON_EXT_DISABLED'] is not set
and run the following command:
 
gem install bson_ext
 
If you continue to receive this message after installing, make sure that
the bson_ext gem is in your load path.
[2015-10-04T14:28:04+00:00] WARN: Cannot configure replicaset 'int-mgo-replset', no member nodes found
[2015-10-04T14:28:04+00:00] INFO: ruby_block[config_replicaset] called
</pre>

May be I miss something cause i'm a newby in Chef config.

Jm

**Comment by jmcollin78** [comment] 2015-10-09 07:03
No idea ? I'm stuck with this issue and I can't get rid of this error.

Many thank's in advance.

**Comment by luishdez** [comment] 2015-10-11 05:29
For sure there is a problem with Mongo Gem but I haven't been able to reproduce it yet…

Take a look to these issues may be you can get some ideas:

https://github.com/chef-brigade/mongodb-cookbook/issues/85
https://github.com/chef-brigade/mongodb-cookbook/issues/41

I have a repo with a vagrant test I've checked with Ubuntu and CentOS but I couldn't reproduce it. 
https://github.com/luishdez/mongodb-cookbook-playground

**Comment by jkulak** [comment] 2015-10-22 16:14
I can reproduce on Ubuntu 14.04.1 LTS (GNU/Linux 4.1.5-x86_64-linode61 x86_64) but it works on Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-63-generic x86_64)

**Comment by jmcollin78** [comment] 2015-10-22 18:17
I'm working with Amazon Linux. Is there any reason for this Linux to not
working like Centos ?

**Comment by damacus** [comment] 2016-12-17 13:09
I'm going to close this issue down. 
This should be fixed during the rewrite. If it isn't covered by the tests please shout.

**Closed by damacus** 2016-12-17 13:09 UTC
Labels: bug
